-- MySQL Script generated by MySQL Workbench
-- Sat Oct  7 21:47:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `UserUsuario` VARCHAR(100) NOT NULL,
  `NomeUsuario` VARCHAR(100) NOT NULL,
  `EmailUsuario` VARCHAR(100) NOT NULL,
  `SenhaUsuario` VARCHAR(100) NOT NULL,
  `FotoUsuario` BLOB NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Turma` (
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `AnoTurma` VARCHAR(50) NOT NULL,
  `NomeTurma` VARCHAR(50) NULL,
  PRIMARY KEY (`idTurma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `NomeAluno` VARCHAR(100) NOT NULL,
  `EmailAluno` VARCHAR(100) NULL,
  `ObsAluno` VARCHAR(250) NULL,
  `Turma_idTurma` INT NOT NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `fk_Aluno_Turma1_idx` (`Turma_idTurma` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `biblioteca`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Prof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Prof` (
  `idProf` INT NOT NULL AUTO_INCREMENT,
  `NomeProf` VARCHAR(100) NOT NULL,
  `EmailProf` VARCHAR(100) NOT NULL,
  `MateriaProf` VARCHAR(50) NULL,
  `ObsProf` VARCHAR(250) NULL,
  PRIMARY KEY (`idProf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Altor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Altor` (
  `idAltor` INT NOT NULL AUTO_INCREMENT,
  `NomeAltor` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAltor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `NomeGenero` VARCHAR(50) NOT NULL,
  `DidaticoGenero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Idioma` (
  `idIdioma` INT NOT NULL AUTO_INCREMENT,
  `Idioma` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idIdioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Livro` (
  `idLivro` INT NOT NULL AUTO_INCREMENT,
  `NomeLivro` VARCHAR(100) NOT NULL,
  `IBSMLivro` VARCHAR(50) NULL,
  `LocalLivro` VARCHAR(250) NULL,
  `Altor_idAltor` INT NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  `Idioma_idIdioma` INT NOT NULL,
  `FotoLivro` BLOB NULL,
  `EditoraLivro` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idLivro`),
  INDEX `fk_Livro_Altor_idx` (`Altor_idAltor` ASC) VISIBLE,
  INDEX `fk_Livro_Genero1_idx` (`Genero_idGenero` ASC) VISIBLE,
  INDEX `fk_Livro_Idioma1_idx` (`Idioma_idIdioma` ASC) VISIBLE,
  CONSTRAINT `fk_Livro_Altor`
    FOREIGN KEY (`Altor_idAltor`)
    REFERENCES `biblioteca`.`Altor` (`idAltor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `biblioteca`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_Idioma1`
    FOREIGN KEY (`Idioma_idIdioma`)
    REFERENCES `biblioteca`.`Idioma` (`idIdioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Empestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Empestimo` (
  `idEmpestimo` INT NOT NULL AUTO_INCREMENT,
  `DataEmprestimo` DATE NOT NULL,
  `StatusEmprestimo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEmpestimo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Devolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Devolucao` (
  `idDevolucao` INT NOT NULL AUTO_INCREMENT,
  `DataDevolucao` DATE NOT NULL,
  `StatusDevolucao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDevolucao`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
